import React, { ReactNode, FC } from "react";
import { Navbar } from "../Navbar/Navbar";
import { Footer } from "../Footer/Footer";
import Head from "next/head";

interface Props {
  children: ReactNode;
}

const Layout: FC<Props> = ({ children }) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex flex-col h-screen w-full">
        <header className="fixed w-full top-0 h-16 z-20">
          <Navbar />
        </header>
        <main className="flex-1 w-full pt-16 pb-16">
          <div className="w-full h-full bg-slate-100 p-5">{children}</div>
        </main>
        <footer className="fixed flex w-full bottom-0 h-16">
          <Footer />
        </footer>
      </div>
    </>
  );
};

export default Layout;
