import React, { ReactNode, FC } from "react";
import { FooterLogin } from "../Footer/FooterLogin";
import Head from "next/head";
import { NavbarEmty } from "../Navbar/NavbarEmpty";
import Image from "next/image";

interface Props {
  children: ReactNode;
}

const LayoutLogin: FC<Props> = ({ children }) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex flex-col h-screen w-full">
        <main className="flex flex-1 w-full overflow-y-auto pb-16 justify-center items-center">
          <div className="fixed inset-0 z-0">
            <Image
              layout="fill"
              objectFit="cover"
              objectPosition="center"
              src="/assets/bg-login.jpg"
              alt="landscape"
            />
          </div>
          <div className="relative z-10 flex content-center justify-center">{children}</div>
        </main>
        <footer className="fixed flex w-full bottom-0 h-14 z-50">
          <FooterLogin />
        </footer>
      </div>
    </>
  );
};

export default LayoutLogin;
